FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

RUN apt update 
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update 
RUN apt install python3.6
RUN apt-get install python3-pip -y
RUN pip3 install --upgrade pip

WORKDIR /app
RUN mkdir models

COPY deepspeech-0.8.1-models.pbmm /app/models  # model from https://github.com/mozilla/DeepSpeech/releases/download/v0.8.1/deepspeech-0.8.1-models.pbmm
COPY deepspeech-0.8.1-models.scorer /app/models # You can get scorer in https://mozilla-voice-stt.readthedocs.io/en/latest/?badge=latest

CMD "bash"